CREATE DATABASE IF NOT EXISTS wkylin_site
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'wkylin'@'localhost' IDENTIFIED BY 'wkylin_password';
CREATE USER IF NOT EXISTS 'wkylin'@'%' IDENTIFIED BY 'wkylin_password';

GRANT ALL PRIVILEGES ON wkylin_site.* TO 'wkylin'@'localhost';
GRANT ALL PRIVILEGES ON wkylin_site.* TO 'wkylin'@'%';

FLUSH PRIVILEGES;

USE wkylin_site;

CREATE TABLE IF NOT EXISTS site_profile (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  payload JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
